#CREATED BY JENYA
version: '3'

services:
  flask-app:
    build: ./the-app
    ports:
      - "5000:5000"
#    depends_on:
#      - mysql
    environment:
      - FLASK_ENV=production
    networks:
      - myappnet

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask-app
    networks:
      - myappnet

networks:
  myappnet:
    driver: bridge
