#CREATED BY JENYA
version: '3.8'

services:
  web:
    build:
      context: ./the-app
    expose:
      - "5000"  # Expose port 5000 to the internal network (accessible by Nginx)
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: your_db_name
      MYSQL_USER: username
      MYSQL_PASSWORD: password

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
